# Generated by Django 5.0.7 on 2024-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='water_strength',
            field=models.CharField(choices=[('5', 'Tsunami Blast'), ('4', 'Power Wash'), ('3', 'Moderate Stream'), ('2', 'Light Drizzle'), ('1', 'Gentle Mist')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
