# Generated by Django 5.0.7 on 2024-07-16 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bidet_water_strength_alter_bidet_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bidet')),
            ],
        ),
    ]
