# Generated by Django 5.0.7 on 2024-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
