# Generated by Django 5.0.7 on 2024-07-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bidet_slug_alter_bidet_address_alter_review_bidet'),
    ]

    operations = [
    ]
