# Generated by Django 5.0.7 on 2024-07-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240716_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidet',
            name='slug',
        ),
    ]
