# Generated by Django 5.0.7 on 2024-07-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_bidet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='bidet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bidet'),
        ),
    ]
