# Generated by Django 5.0.7 on 2024-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_name_alter_review_bidet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
