# Generated by Django 5.0.7 on 2024-07-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bidet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidet',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
