# Generated by Django 5.0.7 on 2024-07-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_bidet_slug_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.bidet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
