# Generated by Django 5.0.7 on 2024-07-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
