# Generated by Django 5.0.7 on 2024-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
