# Generated by Django 5.0.7 on 2024-07-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_bidet_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidet',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
