# Generated by Django 5.0.7 on 2024-07-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_bidet_closing_time_bidet_opening_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
