# Generated by Django 5.0.7 on 2024-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_bidet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidet',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='bidet',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
