# Generated by Django 5.0.7 on 2024-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_bidet_closing_time_remove_bidet_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='handicap_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
