# Generated by Django 5.0.7 on 2024-07-19 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bidet_closing_time_bidet_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidet',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
