# Generated by Django 5.0.7 on 2024-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_bidet_closing_time_alter_bidet_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidet',
            name='closing_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='opening_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
