# Generated by Django 5.0.7 on 2024-07-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_bidet_address_alter_bidet_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidet',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='bidet',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000000),
        ),
    ]
