# Generated by Django 5.0.7 on 2024-07-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_bidet_closing_time_remove_bidet_opening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidet',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidet',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidet',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
